### ISSUE TITLE
Multi-line text

### ISSUE THREAD

**Issue by ktodyruik** [elw00d/consoleframework#12]
Is it possible to display and/or edit multi-line text with one of the widgets?

**Comment by Athari** [comment]
@elw00d My https://github.com/Athari/CsConsoleFormat library supports various formatting features, you can try adapting it to your library to support at least displaying of the text. I've used your layout logic which you adapted from WPF and created a simplified library which supports only formatting, but supports it fully.

**Comment by elw00d** [comment]
Nice lib, @Athari ! Missing formatting features in console apps is real pain now. Thank you, will look at this :smiley_cat:

**Comment by igor-kostromin** [comment]
Basically implemented here https://github.com/elw00d/consoleframework/blob/develop/ConsoleFramework/Controls/TextEditor.cs
