### ISSUE TITLE
Programmatical (vs XAML) example?

### ISSUE THREAD

**Issue by pfalcon** [elw00d/consoleframework#22]
All examples I saw so far use XAML files. Is there example how to code UI programmatically, by instantiate objects and calling methods?

**Comment by elw00d** [comment]
Hello, there are some information about it at this page : http://elw00d.github.io/consoleframework/xaml.html

Also, there are the oldest example program listed in https://github.com/elw00d/consoleframework/blob/master/Examples/Program.cs file

Hope it will help

**Comment by pfalcon** [comment]
That answers it, thanks!
