### ISSUE TITLE
Mouse interaction

### ISSUE THREAD

**Issue by dajuric** [elw00d/consoleframework#23]
I was wondering how do I achieve mouse interaction.
 I have tried all included samples (WIndows Console), but I was unable to interact with TUI elements using mouse.

Does such possibility exists ?

**Comment by elw00d** [comment]
Have you played with `Quick Insert` and `Insert mode` options? `Quick Insert` mode should be off.

![](http://cdn-5.commandwindows.com/graphics/cmdcfg4.gif)

**Comment by dajuric** [comment]
Many thanks!
