### ISSUE TITLE
Examples project not buildable

### ISSUE THREAD

**Issue by davidpodhola** [elw00d/consoleframework#24]
5>C:\Users\david\S\consoleframework\Examples\Program.cs(122,25,122,30): error CS0012: The type 'ObservableList<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Binding, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
5>C:\Users\david\S\consoleframework\Examples\Program.cs(123,25,123,30): error CS0012: The type 'ObservableList<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Binding, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
5>C:\Users\david\S\consoleframework\Examples\Program.cs(153,29,153,34): error CS0012: The type 'ObservableList<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Binding, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by elw00d** [comment]
Strange.. In my Visual Studio 2010 and in Monodevelop all is ok ) What version of Visual Studio are you using ?

**Comment by davidpodhola** [comment]
Visual Studio 2015 Update 1. Seems to be related to [How does Copy-local work? log4net.dll is not being copied to MyProject output directory](http://stackoverflow.com/a/12779924/2013924) - note that they say it is not working in Visual Studio 2013 and newer.

**Comment by elw00d** [comment]
Sorry, I was wrong. I tried to build `master` branch, meanwhile `develop` was really broken. Thanks for submitting patch !
