### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by miyu** [elw00d/consoleframework#29]
Does a NuGet package exist for this project? Googled around for stuff like "ConsoleFramework nuget" and nothing came up.

It's the de-facto way to include external dependencies and necessary for use with e.g. .net core.

**Comment by igor-kostromin** [comment]
Unfortunately, no (yet). Will do this soon

**Comment by YellowOnion** [comment]
Any updates on this?

**Comment by EntityFX** [comment]
When nuget will be available?

**Comment by igor-kostromin** [comment]
NuGet package is available here https://www.nuget.org/packages/Elwood.ConsoleFramework

Sorry for the delay 🤕
