### ISSUE TITLE
Commands binded to Button do not work

### ISSUE THREAD

**Issue by molszews** [elw00d/consoleframework#30]
During development I've noticed that commands binded to buttons are not executed. I thought that it may be something with my code, but the same thing is happening in provided sample apps. However commands are executed correctly when fired from menu.
I am using win10 x64 and it is a bit of showstopper to me.

edit: I've noticed that clicking on button with mouse sometimes does work, hitting enter on keyboard however does not

edit2: registering to button's onClick event works with mouse and with keyboard

**Comment by igor-kostromin** [comment]
Can you show any code reproducing the problem ?

**Comment by molszews** [comment]
Sure, please execute code provided in Examples.Commands on project's github. It is showing button with binded command which shows messagebox. Currently i cannot fire button with keyboard, nor close messagebox (I hava to use mouse in first case).
marek

Date: Tue, 24 May 2016 14:55:54 -0700

**Comment by igor-kostromin** [comment]
Thanks, fixed in `develop`.
About closing message box: there are no logic bound to OK button, unfortunately, will do this too
