### ISSUE TITLE
Discussion: Xaml System?

### ISSUE THREAD

**Issue by Mike-E-angelo** [elw00d/consoleframework#31]
Wow!  What a super cool project.  I am really impressed.  I am curious about your Xaml system and if you are planning (or have considered) either making it its own standalone system, or maybe integrating another external system such as [OmniXaml](https://github.com/SuperJMN/OmniXAML) and/or [Portable.Xaml](https://github.com/cwensley/Portable.Xaml)?

In any case, great work here. :smile:

**Comment by igor-kostromin** [comment]
Well, when I was coding xaml subsystem, there were no crossplatform xaml implementations like these you've mentioned above. For now, it is not easy to make decision to use some of existing implementations. From the other side, my own implementation has some limitations (no inner property access support, no expressions). So, it is dialectically need to look at something better :) but I can't promise something certain right now

**Comment by Mike-E-angelo** [comment]
Cool... good to hear the background and perspective.  FWIW, there is an open issue on CoreFX to port System.Xaml over to it.  With a little luck we might be able to merge all our efforts over time and use the same, powerful Xaml system in all our projects. :)  You can upvote the issue (and/or contribute to the conversation!) here:
https://github.com/dotnet/corefx/issues/5766

**Comment by igor-kostromin** [comment]
Yes, it will be great if System.Xaml will work everywhere, voted up

**Comment by Mike-E-angelo** [comment]
Awesome, thank you!  I will close this thread now to help out with your issue count. :)
