### ISSUE TITLE
.NET Core build

### ISSUE THREAD

**Issue by samirkut** [elw00d/consoleframework#33]
Any plans on making this compatible with the new .NET standard framework. I would like to use this in some of my .NET core apps...

**Comment by igor-kostromin** [comment]
Work in progress, I have created branch https://github.com/elw00d/consoleframework/tree/dotnetcore
But there is one thing that doesnt work: keyboard handling (I suspect that is bug in runtime https://github.com/dotnet/coreclr/issues/8237). Although, I think, it is possible to make some temporary workaround to mitigate this bug. Will do this and will point the 'fixing' commit here in comments.

And another bug it is displaying in console with artifacts. Possibly, that is another bug in interop. But it seems not to be blocker.

**Comment by ForNeVeR** [comment]
I'd actually like to see the library available as .NET Standard artifact, so it could be used either in full .NET or .NET Core programs.

Is that what you were planning, or should I create another issue to discuss that?

**Comment by igor-kostromin** [comment]
Finally, I've merged all this stuff, and all further development will be for .NET Core only. Thank you for your help !
