### ISSUE TITLE
TabControl in example doesn't receive mouse clicks

### ISSUE THREAD

**Issue by patridge** [elw00d/consoleframework#34]
I Loaded up the Examples project and made sure it was set to launch the TabControl sample. When it launched, the tabbed window shows up fine. Unfortunately, clicking on the tabs doesn't seem to change the selected tab.

I tried putting a breakpoint in the [TabControl mouse handler](https://github.com/elw00d/consoleframework/blob/develop/ConsoleFramework/Controls/TabControl.cs#L32), but it was never hit. I then put a breakpoint in the [`ParseInputEvent`](https://github.com/elw00d/consoleframework/blob/develop/ConsoleFramework/Events/EventManager.cs#L232) handler but couldn't get it to hit either.

Is there some extra magic required to get TabControl to handle clicks?

**Comment by igor-kostromin** [comment]
Have you played with `Quick Edit` and `Insert mode` options? `Quick Edit` mode should be off.

![](http://cdn-5.commandwindows.com/graphics/cmdcfg4.gif)

**Comment by patridge** [comment]
I'll give that a shot. Sorry if I missed prerequisite steps somewhere before launching the samples.
