### ISSUE TITLE
Has this great project been discontinued?

### ISSUE THREAD

**Issue by FSharpCSharp** [elw00d/consoleframework#43]
Unfortunately, the last commits of this really outstanding project are almost half a year ago. The project has a lot of potential and has some intuitive mechanisms. So I ask the question, is the project stopped or continued under another name? It would be a real shame if it doesn't go on here. Such a useful project must absolutely be continued and maintained.

**Comment by igor-kostromin** [comment]
Over 6 years there were no real applications appeared that use this library.
So, basically, I think it is something not so needed for society :)
Nevertheless, there is some development in .net core branch. I hope .net core will implement native apps build mode, and this will motivate the further development of whole library.

**Comment by FSharpCSharp** [comment]
@elw00d 
Thanks for the answer. But I have to emphasize again that this project is incredibly well done. This is the only useful console framework for. NET. All the others I've found so far seem like a gimmick to me.
