### ISSUE TITLE
problem with loading xaml

### ISSUE THREAD

**Issue by furesoft** [elw00d/consoleframework#50]
hi, i have a window from xaml all its fine but the controls will not be displayed:
`<my:Window Name="LoginWindow" Title="MissionPack Selection"
        xmlns:x="http://consoleframework.org/xaml.xsd"
        xmlns:my="clr-namespace:ConsoleFramework.Controls;assembly=ConsoleFramework"
        xmlns:converters="clr-namespace:Binding.Converters;assembly=Binding"
        xmlns:xaml="clr-namespace:ConsoleFramework.Xaml;assembly=ConsoleFramework"
        MinWidth="50" MinHeight="50" X="50"  >
  
    <TextBox Text="Text"></TextBox>
    <TextBox Text="Text"></TextBox>

    <Button Caption="Long Button"></Button>
    <ComboBox Name="cb"></ComboBox>
</my:Window>`

**Comment by Xkonti** [comment]
Try putting Panel inside window and all the controls into this panel.

```
<my:Window Name="LoginWindow" Title="MissionPack Selection" 
    xmlns:x="http://consoleframework.org/xaml.xsd" 
    xmlns:my="clr-namespace:ConsoleFramework.Controls;assembly=ConsoleFramework" 
    xmlns:converters="clr-namespace:Binding.Converters;assembly=Binding" 
    xmlns:xaml="clr-namespace:ConsoleFramework.Xaml;assembly=ConsoleFramework" MinWidth="50" MinHeight="50" X="50">
    <Panel>
        <TextBox Text="Text"></TextBox>
        <TextBox Text="Text"></TextBox>
        <Button Caption="Long Button"></Button>
        <ComboBox Name="cb"></ComboBox>
    </Panel>
</my:Window>
```
