### ISSUE TITLE
Create a persistent window.

### ISSUE THREAD

**Issue by nathan130200** [elw00d/consoleframework#51]
Is possible create and show a window that user can't close (allow close only by code)? like a loading screen, keep open when is loading something and close if is done.

Like windows forms event `FormClosingEventArgs` (`e.Cancel = true` keeps form opened)

**Comment by igor-kostromin** [comment]
You can just inherit your window from existing class and add this option. Or modify Window class directly and create PR ;)

**Comment by nathan130200** [comment]
🤦‍♂️
