### ISSUE TITLE
No tag for 0.0.3

### ISSUE THREAD

**Issue by ForNeVeR** [elw00d/consoleframework#70]
While trying to answer your question for #67, I've found out that it's impossible to say for sure which library version I use, since I use 0.0.3 from [NuGet](https://www.nuget.org/packages/Elwood.ConsoleFramework/), and there's no public tag for that version.

I could only guess that most likely it was released from commit 05ff993312a4ce106c66a575d05686361ead92b2. Could you please add the tag?

**Comment by igor-kostromin** [comment]
Done ^_^

https://github.com/elw00d/consoleframework/tree/v0.3-release

**Comment by ForNeVeR** [comment]
Thanks a lot!
